### ISSUE TITLE
Definitions page for various terms maybe?

### ISSUE THREAD

**Issue by PipeItToDevNull** [PipeItToDevNull/rTS_Wiki#3]
I want to remove "shitware" from the places it occurs and replace it with "PUP" but I want to link PUP back to a definition

**Comment by PipeItToDevNull** [comment]
It is already defined on the AV page, we can link this back to that and consider a total definitions page down the road probably

**Comment by SealsRock12** [comment]
We have a definitions page on the [old wiki](https://rtech.support/books/learning/page/abbreviations-commands

**Comment by PipeItToDevNull** [comment]
smart, we can stick with that then
