### ISSUE TITLE
Testing TOC

### ISSUE THREAD

**Issue by PipeItToDevNull** [PipeItToDevNull/rTS_Wiki#6]
I wanted to make sure I understood TOCs, I added one to 

https://github.com/PipeItToDevNull/rTS_Wiki/blob/dev/docs/disks/management.md

https://just-the-docs.github.io/just-the-docs/docs/navigation-structure/#in-page-navigation-with-table-of-contents

**Comment by SealsRock12** [comment]
It doesn't work, however the one I made in [this commit(https://github.com/PipeItToDevNull/rTS_Wiki/commit/9cb5772f02b334302b7005fc4789fd7ab0c45f09) show up like this:
<img width="825" alt="image" src="https://user-images.githubusercontent.com/47796480/174407181-c475f05c-c680-471a-85fc-26778a149066.png">
It is also collapsible with the arrow. However, you still need to add the `{ .no_toc }` to the title.

**Comment by PipeItToDevNull** [comment]
I added the markdown format to readme as well

**Comment by PipeItToDevNull** [comment]
[change numbered list to bulleted](https://github.com/PipeItToDevNull/rTS_Wiki/commit/e54c5e502c4e84c36c3d17c94b21346c23358fde)
